#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:ndt/dotfiles.git"

echo "Checking for ZSH Antigen"
if [ ! -d "~/.zsh/" ]; then
	mkdir ~/.zsh
	if [ ! -f "~/.zsh/antigen.zsh" ]; then
		echo "Installing Antigen"
		curl -L git.io/antigen > ~/.zsh/antigen.zsh
	fi
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
