#!/bin/zsh

alias ls='ls -lah --color=auto --group-directories-first'
alias ll='ls -lh'
alias ldot='ls -ld .*'
alias lsbig='ls -Slh | head'
alias lssmall='ls -Slhr | head'
alias lsnew='ls -tlh | head'
alias lsold='ls -tlhr | head'
