#!/bin/zsh

alias ls='ls --color=tty --group-directories-first'
alias ll='ls -lh'
alias lsbig='ls -lhS | head'
alias lssmall='ls -lhSr | head'
alias lsnew='ls -lht | head'
alias lsold='ls -lhtr | head'

alias ldot='ls -ld .*'
