#!/usr/bin/env sh

# taskwarrior
in='task add +in'

tickle () {
    deadline=$1
    shift
    in +tickle wait:$deadline $@
}
alias tick=tickle

alias think='tickle +1d'
alias rnd='task add +rnd'
#alias rnd='task add +rnd +next +@computer +@online'

webpage_title (){
    wget -qO- "$*" | hxselect -s '\n' -c  'title' 2>/dev/null
}

read_and_review (){
    link="$1"
    title=$(webpage_title $link)
    echo $title
    descr="\"Read and review: $title\""
    id=$(task add +next +rnr "$descr" | sed -n 's/Created task \(.*\)./\1/p')
    task "$id" annotate "$link"
}

alias rnr=read_and_review

alias t='task'
alias taf='task add realm:family'
alias tah='task add realm:hobby'
alias taw='task add realm:work'

